### ISSUE TITLE
Unable to complete

### ISSUE THREAD

**Issue by zhanwu123** [andreemic/guitar-keyboard#1]
Hello, the guitar - the rid_device_info_keyboard I can't compile the past, can you see?

**Comment by zhanwu123** [comment]
Arduino:1.8.9 (Windows 7), ："Arduino Nano, ATmega328P"

In file included from C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:28:0:

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino: In function 'void setup()':

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:45:3: note: in expansion of macro 'Keyboard'

   Keyboard.begin();

   ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino: In function 'void loop()':

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:82:9: note: in expansion of macro 'Keyboard'

         Keyboard.write('\n');

         ^

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:85:9: note: in expansion of macro 'Keyboard'

         Keyboard.write('\t');

         ^

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:92:9: note: in expansion of macro 'Keyboard'

         Keyboard.write(0xB2);

         ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino: In function 'void scaleModeInput(int)':

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:180:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(c); 

     ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino: In function 'void pressWithShift(char)':

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:184:3: note: in expansion of macro 'Keyboard'

   Keyboard.press(KEY_LEFT_SHIFT);

   ^

note_det-discretesampling:184:18: error: 'KEY_LEFT_SHIFT' was not declared in this scope

   Keyboard.press(KEY_LEFT_SHIFT);

                  ^

In file included from C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:28:0:

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:185:3: note: in expansion of macro 'Keyboard'

   Keyboard.press(key);

   ^

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:187:3: note: in expansion of macro 'Keyboard'

   Keyboard.releaseAll();

   ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino: In function 'void stairsModeInput(int)':

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:195:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(c);

     ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino: In function 'void chromaPrint(int)':

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:235:6: note: in expansion of macro 'Keyboard'

      Keyboard.press(c);

      ^

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:236:5: note: in expansion of macro 'Keyboard'

     Keyboard.press(KEY_LEFT_SHIFT);

     ^

note_det-discretesampling:236:20: error: 'KEY_LEFT_SHIFT' was not declared in this scope

     Keyboard.press(KEY_LEFT_SHIFT);

                    ^

In file included from C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:28:0:

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:239:5: note: in expansion of macro 'Keyboard'

     Keyboard.releaseAll();

     ^

d:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar\note_det-discretesampling\note_det-discretesampling.ino:241:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(c);

     ^

exit status 1
'KEY_LEFT_SHIFT' was not declared in this scope

**Comment by andreemic** [comment]
Hey, the [Keyboard library](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/) is only available on boards with the 32u4 chip (Arduino Pro Micro, Arduino Leonardo, etc.).

I had the pro micro since it has a similar form factor and price range to the nano.

**Comment by zhanwu123** [comment]
Arduino:1.8.9 (Windows 7), ："Arduino/Genuino Uno"


In file included from C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:28:0:

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void setup()':

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:48:3: note: in expansion of macro 'Keyboard'

   Keyboard.begin();

   ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void loop()':

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:55:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(65);

     ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void setup()':

note_det-discretesampling:59:6: error: redefinition of 'void setup()'

 void setup() {

      ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:43:6: note: 'void setup()' previously defined here

 void setup() {

      ^

In file included from C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:28:0:

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:62:3: note: in expansion of macro 'Keyboard'

   Keyboard.begin();

   ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void loop()':

note_det-discretesampling:71:6: error: redefinition of 'void loop()'

 void loop() {

      ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:51:6: note: 'void loop()' previously defined here

 void loop() {

      ^

In file included from C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:28:0:

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:99:9: note: in expansion of macro 'Keyboard'

         Keyboard.write('\n');

         ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:102:9: note: in expansion of macro 'Keyboard'

         Keyboard.write('\t');

         ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:109:9: note: in expansion of macro 'Keyboard'

         Keyboard.write(0xB2);

         ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void scaleModeInput(int)':

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:197:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(c); 

     ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void pressWithShift(char)':

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:201:3: note: in expansion of macro 'Keyboard'

   Keyboard.press(KEY_LEFT_SHIFT);

   ^

note_det-discretesampling:201:18: error: 'KEY_LEFT_SHIFT' was not declared in this scope

   Keyboard.press(KEY_LEFT_SHIFT);

                  ^

In file included from C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:28:0:

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:202:3: note: in expansion of macro 'Keyboard'

   Keyboard.press(key);

   ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:204:3: note: in expansion of macro 'Keyboard'

   Keyboard.releaseAll();

   ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void stairsModeInput(int)':

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:212:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(c);

     ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino: In function 'void chromaPrint(int)':

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:252:5: note: in expansion of macro 'Keyboard'

     Keyboard.press(KEY_LEFT_SHIFT);

     ^

note_det-discretesampling:252:20: error: 'KEY_LEFT_SHIFT' was not declared in this scope

     Keyboard.press(KEY_LEFT_SHIFT);

                    ^

In file included from C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:28:0:

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:253:5: note: in expansion of macro 'Keyboard'

     Keyboard.press(c);

     ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:255:5: note: in expansion of macro 'Keyboard'

     Keyboard.releaseAll();

     ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\libraries\libraries\Keyboard\src/Keyboard.h:23:17: error: expected primary-expression before '.' token

 #define Keyboard.h

                 ^

C:\Users\Administrator\Desktop\guitar-keyboard-main\note_det-discretesampling\note_det-discretesampling.ino:257:5: note: in expansion of macro 'Keyboard'

     Keyboard.write(c);

     ^

exit status 1
redefinition of 'void setup()'

**Comment by zhanwu123** [comment]
I'm sorry, I work is not good, but I love this project!

**Comment by andreemic** [comment]
> I'm sorry, I work is not good, but I love this project!

No problem. Check out the YT video in the Readme to see it in action
